### ISSUE TITLE
Minor issue with classpath scanning dependency

### ISSUE THREAD

**Issue by tommyettinger** [crashinvaders/gdx-lml#4]
In this build.gradle file, https://github.com/crashinvaders/gdx-lml/blob/02e46856b0c011c895162f09d169bc039b360b51/autumn/natives/desktop/fcs/build.gradle#L9 , the dependency `implementation "io.github.lukehutch:fast-classpath-scanner:2.21"` uses `implementation`, but at least in the one place I use it, in gdx-liftoff, some types from the `fast-classpath-scanner` dependency are needed outside of this project. This is easily resolved in Liftoff by adding `implementation "io.github.lukehutch:fast-classpath-scanner:2.21"` to my Gradle dependencies (I could use `api` instead if I was making a library, but Liftoff is an application). I just wanted to point this out here in case you want to change to `api`, or for other people googling this issue to find a fix.

For posterity, the error I encountered when running a JAR built with the desktop fcs code was:

```
$ java -jar gdx-liftoff-1.12.0.1.jar
Exception in thread "main" java.lang.NoClassDefFoundError: io/github/lukehutch/fastclasspathscanner/matchprocessor/ClassAnnotationMatchProcessor
        at gdx.liftoff.MainKt.main(main.kt:123)
        at gdx.liftoff.MainKt.main(main.kt)
Caused by: java.lang.ClassNotFoundException: io.github.lukehutch.fastclasspathscanner.matchprocessor.ClassAnnotationMatchProcessor
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 2 more
```

**Comment by metaphore** [comment]
Sounds logical, thanks.
I'll make a similar change for the most of the leaf modules.
Not sure thought if this requires a new release. At this point there's nothing else to include. I guess it will just sit and wait in the snapshot for now.
